/**
 * topics/flex/challenges.js — 챌린지 8건 (F-09)
 *
 * 1~8 은 v0.1 js/data.js 의 CHALLENGES 를 옮긴 것이다. 제목 · 난이도 · 설명 ·
 * 힌트 · target · ignore · itemCount · miniStyle 은 한 글자도 고치지 않았다.
 * 회귀 검증(PRD 7.1)에서 v0.1 화면과 나란히 대조해야 한다.
 *
 * 9~40 은 v1.0 에서 더한 것이다. 난이도는 바꿔야 하는 속성 수를 따른다 —
 * ⭐ 하나(9~20), ⭐⭐ 둘(21~32), ⭐⭐⭐ 셋 이상이거나 align-content 가 얽힌
 * 것(33~40).
 *
 * align-content 를 묻는 문제는 ignore 에서 alignContent 를 빼고 gap 만 남긴다.
 * 그 속성이 채점 대상이라는 뜻이다.
 *
 * colors 만 accents 로 바꿨다. v0.1 은 아이템 색을 hex 배열로 들고 있어
 * CLAUDE.md 규칙 5 를 어긴다. 다행히 그 값들은 전부 tokens.css 의
 * --p-item-1..8 과 같은 색이었다 — v0.1 의 COLORS 배열이 그대로 토큰이 된 것이다.
 * 그래서 색을 버리지 않고 순번으로 옮겼다. 화면에 나오는 색은 v0.1 과 똑같고,
 * 어느 색인지는 css/components.css 가 --fgp-item-N 으로 고른다.
 *
 * 8번의 itemWidths · itemGrows 는 그 문제에만 있는 값이다. 목표 미리보기에서
 * 사이드바 폭 고정과 본문 확장을 보여 주므로 함께 옮겼다.
 *
 * target 의 키는 스키마의 jsProp 이다. 오타가 나면 정답을 맞혀도 통과하지
 * 못하므로 tools/check-challenges.mjs 가 실제 스키마와 대조한다.
 */

export const FLEX_CHALLENGES = [
    {
      id: 1, title: '정중앙 배치', difficulty: '⭐',
      desc: '아이템 3개를 컨테이너 정중앙(가로 & 세로 모두)에 배치하세요.',
      hint: 'justify-content: center + align-items: center 를 동시에 설정하세요.',
      target: { flexDirection:'row', flexWrap:'nowrap', justifyContent:'center', alignItems:'center' },
      ignore: ['alignContent', 'gap'],
      itemCount: 3,
      accents: [1,2,3],
      miniStyle: { justifyContent:'center', alignItems:'center', height:'54px' },
    },
    {
      id: 2, title: '양끝 정렬 (네비게이션)', difficulty: '⭐',
      desc: '아이템을 좌우 양끝으로 나눠 배치하세요.',
      hint: 'justify-content: space-between 을 사용하세요.',
      target: { flexDirection:'row', flexWrap:'nowrap', justifyContent:'space-between', alignItems:'center' },
      ignore: ['alignContent', 'gap'],
      itemCount: 3,
      accents: [1,5,2],
      miniStyle: { justifyContent:'space-between', alignItems:'center', height:'40px' },
    },
    {
      id: 3, title: '세로 쌓기 (열 방향)', difficulty: '⭐',
      desc: '아이템들이 세로로 쌓이도록 방향을 바꿔보세요.',
      hint: 'flex-direction: column 을 설정하세요.',
      target: { flexDirection:'column', flexWrap:'nowrap', justifyContent:'flex-start', alignItems:'stretch' },
      ignore: ['alignContent', 'gap'],
      itemCount: 3,
      accents: [1,2,3],
      miniStyle: { flexDirection:'column', alignItems:'stretch', gap:'4px', height:'70px' },
    },
    {
      id: 4, title: '줄 바꿈 그리드', difficulty: '⭐⭐',
      desc: '아이템이 넘치면 다음 줄로 내려가게 하세요.',
      hint: 'flex-wrap: wrap 을 설정하세요.',
      target: { flexDirection:'row', flexWrap:'wrap', justifyContent:'flex-start', alignItems:'flex-start' },
      ignore: ['alignContent', 'gap'],
      itemCount: 3,
      accents: [1,2,3],
      miniStyle: { flexWrap:'wrap', alignItems:'flex-start', gap:'4px', height:'auto' },
    },
    {
      id: 5, title: '균등 분배', difficulty: '⭐⭐',
      desc: '아이템 사이 간격을 포함해 모두 동일하게 분배하세요.',
      hint: 'justify-content: space-evenly 를 사용하세요.',
      target: { flexDirection:'row', flexWrap:'nowrap', justifyContent:'space-evenly', alignItems:'center' },
      ignore: ['alignContent', 'gap'],
      itemCount: 4,
      accents: [1,2,3,4],
      miniStyle: { justifyContent:'space-evenly', alignItems:'center', height:'44px' },
    },
    {
      id: 6, title: '역방향 배치', difficulty: '⭐⭐',
      desc: '아이템이 오른쪽에서 왼쪽 순서로 나타나게 하세요.',
      hint: 'flex-direction: row-reverse 를 설정하세요.',
      target: { flexDirection:'row-reverse', flexWrap:'nowrap', justifyContent:'flex-start', alignItems:'center' },
      ignore: ['alignContent', 'gap'],
      itemCount: 3,
      accents: [1,2,3],
      miniStyle: { flexDirection:'row-reverse', alignItems:'center', height:'44px' },
    },
    {
      id: 7, title: '하단 정렬', difficulty: '⭐⭐⭐',
      desc: '아이템을 컨테이너 아래쪽에 붙여 배치하세요.',
      hint: 'align-items: flex-end 를 사용하세요. (주축이 row일 때 교차축이 세로입니다)',
      target: { flexDirection:'row', flexWrap:'nowrap', justifyContent:'flex-start', alignItems:'flex-end' },
      ignore: ['alignContent', 'gap'],
      itemCount: 3,
      accents: [1,2,3],
      miniStyle: { alignItems:'flex-end', height:'60px' },
    },
    {
      id: 8, title: '사이드바 레이아웃', difficulty: '⭐⭐⭐',
      desc: '첫 아이템은 고정 너비, 두 번째 아이템은 남은 공간을 채우게 하세요.',
      hint: 'align-items: stretch + (아이템2에 flex-grow:1 적용)',
      target: { flexDirection:'row', flexWrap:'nowrap', justifyContent:'flex-start', alignItems:'stretch' },
      ignore: ['alignContent', 'gap'],
      itemCount: 2,
      accents: [1,2],
      miniStyle: { alignItems:'stretch', height:'52px' },
      itemWidths: ['40px','auto'],
      itemGrows: [0, 1],
    },
  /* ===================== ⭐ 단일 속성 (9~20) ===================== */
  {
    id: 9, title: '오른쪽 끝으로', difficulty: '⭐',
    desc: '아이템 3개를 컨테이너 오른쪽 끝에 붙이세요.',
    hint: 'justify-content 로 주축 끝점에 붙일 수 있습니다.',
    target: { flexDirection: 'row', flexWrap: 'nowrap', justifyContent: 'flex-end', alignItems: 'center' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [2, 4, 6],
    miniStyle: { justifyContent: 'flex-end', alignItems: 'center', height: '44px' },
  },
  {
    id: 10, title: '여백으로 감싸기', difficulty: '⭐',
    desc: '각 아이템 양옆에 같은 여백을 두세요. 바깥쪽 여백은 사이 여백의 절반이 됩니다.',
    hint: 'space-between · space-around · space-evenly 는 여백 분배 방식이 서로 다릅니다.',
    target: { flexDirection: 'row', flexWrap: 'nowrap', justifyContent: 'space-around', alignItems: 'center' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [1, 3, 5],
    miniStyle: { justifyContent: 'space-around', alignItems: 'center', height: '44px' },
  },
  {
    id: 11, title: '위쪽에 붙이기', difficulty: '⭐',
    desc: '아이템을 교차축 시작점, 즉 컨테이너 위쪽에 붙이세요.',
    hint: 'align-items 가 교차축 정렬을 맡습니다.',
    target: { flexDirection: 'row', flexWrap: 'nowrap', justifyContent: 'flex-start', alignItems: 'flex-start' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [4, 5, 6],
    miniStyle: { justifyContent: 'flex-start', alignItems: 'flex-start', height: '56px' },
  },
  {
    id: 12, title: '기준선 맞추기', difficulty: '⭐',
    desc: '크기가 제각각인 아이템의 텍스트 아랫줄을 나란히 맞추세요.',
    hint: '글자가 놓인 선을 기준으로 삼는 값이 있습니다.',
    target: { flexDirection: 'row', flexWrap: 'nowrap', justifyContent: 'flex-start', alignItems: 'baseline' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [3, 7, 8],
    miniStyle: { justifyContent: 'flex-start', alignItems: 'baseline', height: '56px' },
  },
  {
    id: 13, title: '세로 역순 쌓기', difficulty: '⭐',
    desc: '아이템이 아래에서 위로 쌓이게 하세요. 1번이 맨 아래입니다.',
    hint: 'flex-direction 에는 방향을 뒤집는 값이 있습니다.',
    target: { flexDirection: 'column-reverse', flexWrap: 'nowrap', justifyContent: 'flex-start', alignItems: 'stretch' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [1, 2, 3],
    miniStyle: { flexDirection: 'column-reverse', justifyContent: 'flex-start', alignItems: 'stretch', height: '72px' },
  },
  {
    id: 14, title: '줄 넘김 허용', difficulty: '⭐',
    desc: '아이템이 한 줄에 다 들어가지 않을 때 다음 줄로 넘어가게 하세요.',
    hint: '기본값 nowrap 은 아이템을 줄여서라도 한 줄에 넣습니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start', alignItems: 'stretch' },
    ignore: ['alignContent', 'gap'],
    itemCount: 6,
    accents: [1, 2, 3, 4, 5, 6],
    miniStyle: { flexWrap: 'wrap', justifyContent: 'flex-start', alignItems: 'stretch', height: '72px' },
  },
  {
    id: 15, title: '아래에서부터 줄 쌓기', difficulty: '⭐',
    desc: '줄이 넘어갈 때 새 줄이 위가 아니라 아래에서부터 쌓이게 하세요.',
    hint: 'flex-wrap 에도 방향을 뒤집는 값이 있습니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap-reverse', justifyContent: 'flex-start', alignItems: 'stretch' },
    ignore: ['alignContent', 'gap'],
    itemCount: 6,
    accents: [2, 3, 4, 5, 6, 7],
    miniStyle: { flexWrap: 'wrap-reverse', justifyContent: 'flex-start', alignItems: 'stretch', height: '72px' },
  },
  {
    id: 16, title: '가운데 한 줄', difficulty: '⭐',
    desc: '세로로 쌓인 아이템을 컨테이너 세로 가운데에 모으세요.',
    hint: 'column 에서는 주축이 세로입니다. 주축 정렬은 justify-content 가 맡습니다.',
    target: { flexDirection: 'column', flexWrap: 'nowrap', justifyContent: 'center', alignItems: 'stretch' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [5, 6, 7],
    miniStyle: { flexDirection: 'column', justifyContent: 'center', alignItems: 'stretch', height: '80px' },
  },
  {
    id: 17, title: '세로 양끝으로', difficulty: '⭐',
    desc: '세로로 쌓인 아이템의 첫 번째는 맨 위, 마지막은 맨 아래에 붙이세요.',
    hint: 'column 에서도 주축 정렬 값의 이름은 같습니다.',
    target: { flexDirection: 'column', flexWrap: 'nowrap', justifyContent: 'space-between', alignItems: 'stretch' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [1, 4, 7],
    miniStyle: { flexDirection: 'column', justifyContent: 'space-between', alignItems: 'stretch', height: '80px' },
  },
  {
    id: 18, title: '열의 오른쪽 정렬', difficulty: '⭐',
    desc: '세로로 쌓인 아이템을 오른쪽에 붙이세요. 아이템 폭은 내용만큼만 차지합니다.',
    hint: 'column 에서 교차축은 가로입니다. align-items 를 보세요.',
    target: { flexDirection: 'column', flexWrap: 'nowrap', justifyContent: 'flex-start', alignItems: 'flex-end' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [3, 4, 5],
    miniStyle: { flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'flex-end', height: '80px' },
  },
  {
    id: 19, title: '열의 가운데 정렬', difficulty: '⭐',
    desc: '세로로 쌓인 아이템을 가로 가운데에 맞추세요.',
    hint: '주축이 세로면 교차축은 가로입니다.',
    target: { flexDirection: 'column', flexWrap: 'nowrap', justifyContent: 'flex-start', alignItems: 'center' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [6, 7, 8],
    miniStyle: { flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'center', height: '80px' },
  },
  {
    id: 20, title: '역방향 양끝', difficulty: '⭐',
    desc: '아이템 순서를 오른쪽에서 왼쪽으로 뒤집고, 양끝에 붙이세요. 1번이 오른쪽 끝입니다.',
    hint: 'row-reverse 에서는 주축의 시작점이 오른쪽입니다.',
    target: { flexDirection: 'row-reverse', flexWrap: 'nowrap', justifyContent: 'space-between', alignItems: 'center' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [8, 1, 2],
    miniStyle: { flexDirection: 'row-reverse', justifyContent: 'space-between', alignItems: 'center', height: '44px' },
  },

  /* ===================== ⭐⭐ 두 속성 조합 (21~32) ===================== */
  {
    id: 21, title: '우측 하단 배치', difficulty: '⭐⭐',
    desc: '아이템을 컨테이너 오른쪽 아래 구석에 모으세요.',
    hint: '주축과 교차축을 각각 끝점으로 보내면 됩니다.',
    target: { flexDirection: 'row', flexWrap: 'nowrap', justifyContent: 'flex-end', alignItems: 'flex-end' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [2, 5, 8],
    miniStyle: { justifyContent: 'flex-end', alignItems: 'flex-end', height: '64px' },
  },
  {
    id: 22, title: '우측 상단 배치', difficulty: '⭐⭐',
    desc: '아이템을 컨테이너 오른쪽 위 구석에 모으세요.',
    hint: '주축은 끝점, 교차축은 시작점입니다.',
    target: { flexDirection: 'row', flexWrap: 'nowrap', justifyContent: 'flex-end', alignItems: 'flex-start' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [4, 6, 1],
    miniStyle: { justifyContent: 'flex-end', alignItems: 'flex-start', height: '64px' },
  },
  {
    id: 23, title: '가로 가운데 · 아래 정렬', difficulty: '⭐⭐',
    desc: '아이템을 가로로는 가운데, 세로로는 바닥에 붙이세요.',
    hint: '두 축의 값을 서로 다르게 주어야 합니다.',
    target: { flexDirection: 'row', flexWrap: 'nowrap', justifyContent: 'center', alignItems: 'flex-end' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [7, 8, 1],
    miniStyle: { justifyContent: 'center', alignItems: 'flex-end', height: '64px' },
  },
  {
    id: 24, title: '세로 정중앙', difficulty: '⭐⭐',
    desc: '세로로 쌓인 아이템을 가로·세로 모두 정중앙에 두세요.',
    hint: 'column 에서 justify-content 는 세로, align-items 는 가로를 맡습니다.',
    target: { flexDirection: 'column', flexWrap: 'nowrap', justifyContent: 'center', alignItems: 'center' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [1, 5, 3],
    miniStyle: { flexDirection: 'column', justifyContent: 'center', alignItems: 'center', height: '84px' },
  },
  {
    id: 25, title: '세로 균등 분배', difficulty: '⭐⭐',
    desc: '세로로 쌓인 아이템 사이 간격을 위아래 여백까지 완전히 균등하게 만드세요.',
    hint: 'space-between · space-around · space-evenly 중 하나입니다. 바깥 여백까지 같아야 합니다.',
    target: { flexDirection: 'column', flexWrap: 'nowrap', justifyContent: 'space-evenly', alignItems: 'center' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [2, 4, 6],
    miniStyle: { flexDirection: 'column', justifyContent: 'space-evenly', alignItems: 'center', height: '84px' },
  },
  {
    id: 26, title: '줄바꿈 카드 가운데', difficulty: '⭐⭐',
    desc: '아이템이 여러 줄로 넘어가되, 각 줄이 가로 가운데에 모이게 하세요.',
    hint: '줄 넘김을 켠 뒤 주축 정렬을 조정합니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', alignItems: 'flex-start' },
    ignore: ['alignContent', 'gap'],
    itemCount: 7,
    accents: [1, 2, 3, 4, 5, 6, 7],
    miniStyle: { flexWrap: 'wrap', justifyContent: 'center', alignItems: 'flex-start', height: '76px' },
  },
  {
    id: 27, title: '줄바꿈 우측 정렬', difficulty: '⭐⭐',
    desc: '여러 줄로 넘어가는 아이템을 각 줄마다 오른쪽에 붙이세요.',
    hint: '마지막 줄이 오른쪽으로 밀리는 모습이 됩니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-end', alignItems: 'flex-start' },
    ignore: ['alignContent', 'gap'],
    itemCount: 7,
    accents: [3, 4, 5, 6, 7, 8, 1],
    miniStyle: { flexWrap: 'wrap', justifyContent: 'flex-end', alignItems: 'flex-start', height: '76px' },
  },
  {
    id: 28, title: '역방향 가운데', difficulty: '⭐⭐',
    desc: '아이템 순서를 뒤집고 가로 가운데에 모으세요. 1번이 오른쪽입니다.',
    hint: '방향을 뒤집어도 center 는 여전히 가운데입니다.',
    target: { flexDirection: 'row-reverse', flexWrap: 'nowrap', justifyContent: 'center', alignItems: 'center' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [5, 7, 2],
    miniStyle: { flexDirection: 'row-reverse', justifyContent: 'center', alignItems: 'center', height: '52px' },
  },
  {
    id: 29, title: '역방향 하단 정렬', difficulty: '⭐⭐',
    desc: '아이템을 오른쪽에서 왼쪽 순서로 배치하되, 바닥에 붙이세요.',
    hint: '방향 뒤집기와 교차축 끝점 정렬을 함께 씁니다.',
    target: { flexDirection: 'row-reverse', flexWrap: 'nowrap', justifyContent: 'flex-start', alignItems: 'flex-end' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [6, 3, 8],
    miniStyle: { flexDirection: 'row-reverse', justifyContent: 'flex-start', alignItems: 'flex-end', height: '64px' },
  },
  {
    id: 30, title: '뒤집힌 줄 · 가운데', difficulty: '⭐⭐',
    desc: '줄이 아래에서부터 쌓이면서, 각 줄은 가로 가운데에 모이게 하세요.',
    hint: 'wrap 의 방향을 뒤집는 값과 주축 가운데 정렬을 함께 씁니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap-reverse', justifyContent: 'center', alignItems: 'flex-start' },
    ignore: ['alignContent', 'gap'],
    itemCount: 7,
    accents: [8, 7, 6, 5, 4, 3, 2],
    miniStyle: { flexWrap: 'wrap-reverse', justifyContent: 'center', alignItems: 'flex-start', height: '76px' },
  },
  {
    id: 31, title: '열 방향 하단 정렬', difficulty: '⭐⭐',
    desc: '세로로 쌓인 아이템을 컨테이너 바닥에 붙이세요.',
    hint: 'column 에서 바닥은 주축의 끝점입니다.',
    target: { flexDirection: 'column', flexWrap: 'nowrap', justifyContent: 'flex-end', alignItems: 'stretch' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [4, 2, 7],
    miniStyle: { flexDirection: 'column', justifyContent: 'flex-end', alignItems: 'stretch', height: '84px' },
  },
  {
    id: 32, title: '세로 여백 감싸기', difficulty: '⭐⭐',
    desc: '세로로 쌓인 아이템 각각의 위아래에 같은 여백을 두세요. 바깥 여백은 절반이 됩니다.',
    hint: 'space-evenly 와 헷갈리기 쉽습니다. 바깥 여백 크기를 보세요.',
    target: { flexDirection: 'column', flexWrap: 'nowrap', justifyContent: 'space-around', alignItems: 'center' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [1, 6, 4],
    miniStyle: { flexDirection: 'column', justifyContent: 'space-around', alignItems: 'center', height: '84px' },
  },

  /* ============ ⭐⭐⭐ 세 속성 이상 · alignContent (33~40) ============ */
  {
    id: 33, title: '줄 뭉치 가운데', difficulty: '⭐⭐⭐',
    desc: '여러 줄로 넘어간 아이템 전체를 세로 가운데에 모으세요. 줄과 줄 사이는 붙어 있어야 합니다.',
    hint: '각 줄 안의 정렬이 아니라 줄 뭉치 전체를 움직이는 속성이 따로 있습니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', alignItems: 'center', alignContent: 'center' },
    ignore: ['gap'],
    itemCount: 7,
    accents: [1, 2, 3, 4, 5, 6, 7],
    miniStyle: { flexWrap: 'wrap', justifyContent: 'center', alignItems: 'center', alignContent: 'center', height: '84px' },
  },
  {
    id: 34, title: '줄 뭉치 양끝', difficulty: '⭐⭐⭐',
    desc: '첫 줄은 맨 위, 마지막 줄은 맨 아래에 붙이고 줄 사이 간격을 균등하게 나누세요.',
    hint: 'align-content 에도 space- 계열 값이 있습니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start', alignItems: 'flex-start', alignContent: 'space-between' },
    ignore: ['gap'],
    itemCount: 7,
    accents: [2, 3, 4, 5, 6, 7, 8],
    miniStyle: { flexWrap: 'wrap', justifyContent: 'flex-start', alignItems: 'flex-start', alignContent: 'space-between', height: '84px' },
  },
  {
    id: 35, title: '줄 뭉치 하단', difficulty: '⭐⭐⭐',
    desc: '여러 줄로 넘어간 아이템 전체를 컨테이너 바닥에 붙이세요.',
    hint: '줄 뭉치를 교차축 끝점으로 보냅니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start', alignItems: 'flex-start', alignContent: 'flex-end' },
    ignore: ['gap'],
    itemCount: 7,
    accents: [5, 6, 7, 8, 1, 2, 3],
    miniStyle: { flexWrap: 'wrap', justifyContent: 'flex-start', alignItems: 'flex-start', alignContent: 'flex-end', height: '84px' },
  },
  {
    id: 36, title: '태그 목록', difficulty: '⭐⭐⭐',
    desc: '태그가 왼쪽부터 채워지고 넘치면 다음 줄로 넘어가되, 줄 뭉치는 위쪽에 붙어 있어야 합니다.',
    hint: '줄 넘김 · 주축 시작 · 교차축 시작 · 줄 뭉치 시작을 모두 맞춰야 합니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start', alignItems: 'flex-start', alignContent: 'flex-start' },
    ignore: ['gap'],
    itemCount: 8,
    accents: [1, 2, 3, 4, 5, 6, 7, 8],
    miniStyle: { flexWrap: 'wrap', justifyContent: 'flex-start', alignItems: 'flex-start', alignContent: 'flex-start', height: '84px' },
  },
  {
    id: 37, title: '갤러리 정중앙', difficulty: '⭐⭐⭐',
    desc: '여러 줄의 아이템을 가로·세로 모두 정중앙에 모으고, 각 줄 안에서도 가운데에 맞추세요.',
    hint: 'justify-content · align-items · align-content 세 가지를 모두 씁니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-evenly', alignItems: 'center', alignContent: 'center' },
    ignore: ['gap'],
    itemCount: 6,
    accents: [3, 5, 7, 2, 4, 6],
    miniStyle: { flexWrap: 'wrap', justifyContent: 'space-evenly', alignItems: 'center', alignContent: 'center', height: '84px' },
  },
  {
    id: 38, title: '푸터 3분할', difficulty: '⭐⭐⭐',
    desc: '푸터 영역을 세 덩이로 나눠 각 덩이 양옆에 같은 여백을 두고, 세로로는 바닥에 붙이세요.',
    hint: '주축은 space- 계열, 교차축은 끝점입니다.',
    target: { flexDirection: 'row', flexWrap: 'nowrap', justifyContent: 'space-around', alignItems: 'flex-end' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [6, 1, 4],
    miniStyle: { justifyContent: 'space-around', alignItems: 'flex-end', height: '64px' },
  },
  {
    id: 39, title: '역순 세로 스택', difficulty: '⭐⭐⭐',
    desc: '아이템이 아래에서 위로 쌓이고, 가로 가운데에 맞추며, 세로로는 균등 간격을 두세요.',
    hint: 'column-reverse 에서 주축 시작점은 아래쪽입니다.',
    target: { flexDirection: 'column-reverse', flexWrap: 'nowrap', justifyContent: 'space-evenly', alignItems: 'center' },
    ignore: ['alignContent', 'gap'],
    itemCount: 3,
    accents: [8, 5, 2],
    miniStyle: { flexDirection: 'column-reverse', justifyContent: 'space-evenly', alignItems: 'center', height: '84px' },
  },
  {
    id: 40, title: '뒤집힌 줄 · 양끝 뭉치', difficulty: '⭐⭐⭐',
    desc: '줄이 아래에서부터 쌓이고, 각 줄은 양끝에 붙으며, 줄 뭉치는 위아래로 벌어지게 하세요.',
    hint: 'wrap-reverse 에서는 align-content 의 방향도 함께 뒤집힙니다.',
    target: { flexDirection: 'row', flexWrap: 'wrap-reverse', justifyContent: 'space-between', alignItems: 'center', alignContent: 'space-between' },
    ignore: ['gap'],
    itemCount: 7,
    accents: [7, 6, 5, 4, 3, 2, 1],
    miniStyle: { flexWrap: 'wrap-reverse', justifyContent: 'space-between', alignItems: 'center', alignContent: 'space-between', height: '84px' },
  },
];

export default FLEX_CHALLENGES;
